### PR TITLE
adds multilingual to alert banners

### LINKED ISSUE #13: Allow Alert Banners to be translated
-  [x] Alert banners

### PR DESCRIPTION
**Pull request by markconroy**
Closes #13

### CODE REVIEW

**Comment by andybroomfield** [comment]
Is multilingual just enabling some default configuration to say alert banners are translateable, or does it need to make adjustments to the entity? Just trying to understand the implications of having this in the multilingual module and not the alert banner module. Would others be able to set up translations of alert banners without this module and this PR is just automating that process?

**Comment by markconroy** [comment]
> Is multilingual just enabling some default configuration to say alert banners are translateable, 
- yes

> or does it need to make adjustments to the entity? 
- no

> Just trying to understand the implications of having this in the multilingual module and not the alert banner module. 
- The reasoning is so that all the multilingual stuff is in one place. Most people using alert banners won't need the multilingual part, but most people using multilingual will want all the parts.
 
> Would others be able to set up translations of alert banners without this module 
- Yes 

> and this PR is just automating that process?
- Yes

**Comment by finnlewis** [comment]
@andybroomfield mentions in Merge Monday that this will need an $is_synching in the hook_install and to bail out if it is. 

See https://github.com/localgovdrupal/localgov_directories/blob/2.x/modules/localgov_directories_location/localgov_directories_location.install#L21-L25

**Comment by markconroy** [comment]
Thanks @andybroomfield. Good catch. 

I've added `$is_syncing` to this and all the other `.install` files now.

**Review by andybroomfield — APPROVED** [review]

**Pull request merged**
